markdown_extensions:
- attr_list
- md_in_html
- tables
- fenced_code
- toc:
    permalink: true
plugins:
- search
site_name: 'ISOBUS Virtual Terminal: Benutzeroberfläche und Objekte (2)'
site_url: https://docs.ms-muc-docs.de/projects/ISOBUS-VT-Objects-docs/
repo_url: https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/ISOBUS-VT-Objects-docs
edit_uri: edit/main/docs/
view_uri: blob/main/docs/
theme:
  features:
  - navigation.sections
  - navigation.expand
  - search.suggest
  - search.highlight
  - content.action.edit
  - content.action.view
  language: de
  name: material
  palette:
  - accent: indigo
    primary: indigo
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - accent: indigo
    primary: indigo
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
